all:
	gcc -o serial tema1_serial.c
	gcc -o paralel -fopenmp tema1_paralel.c

serial:
	gcc -o serial tema1_serial.c
	
paralel:
	gcc -o paralel -fopenmp tema1_paralel.c

clean:
	rm -rf serial
	rm -rf paralel
